from __future__ import annotations

from typing import Any


def system_catalog() -> dict[str, Any]:
    return {
        "name": "ValiFixTest & TSGColAgent",
        "runtime": "LangGraph StateGraph",
        "architecture": [
            {"layer": "智能体执行层", "responsibility": "三个顶层智能体通过LangGraph条件路由围绕共享TSG协作。"},
            {"layer": "实验数据层", "responsibility": "保存任务测试、状态、覆盖、变异、轮次、失败和批量统计产物。"},
            {"layer": "监控服务层", "responsibility": "登记实验、启动队列、融合实时产物、提供受限文件访问和知识问答接口。"},
            {"layer": "交互展示层", "responsibility": "实时展示实验、测试状态、智能体交互、生成过程、任务报告和测试知识引导库。"},
        ],
        "entrypoints": [
            {"name": "单文件或单类", "command": "python -B main.py --source <源码> --out <输出目录> --llm", "file": "main.py"},
            {"name": "单目录或单项目", "command": "python -B batch_generate_tests.py --source-dir <目录> --out <输出目录> --execute --recursive --llm", "file": "batch_generate_tests.py"},
            {"name": "完整数据集集合", "command": "python -B run_all_datasets.py --datasets-root <数据集根目录> --out-root <实验根目录> --llm --knowledge-store <外置知识文件>", "file": "run_all_datasets.py"},
            {"name": "前端启动实验", "command": "在启动实验页提交单文件、目录或数据集任务", "file": "monitoring/server.py"},
        ],
        "component_map": [
            {"path": "core/experiment_outcome.py", "responsibility": "定义A-E结果、R1/R2/R3进入条件和有效结果统计。"},
            {"path": "orchestration/test_workflow.py", "responsibility": "组织状态分析、知识检索、生成、验证、评估、修复和C级定向优化。"},
            {"path": "agents/test_state_agent.py", "responsibility": "测试状态智能体的状态治理、质量评价、失败归因和下一任务规划。"},
            {"path": "agents/execution_agent.py + agents/repair_agent.py", "responsibility": "测试生成智能体的生成、执行、验证、状态定位修复和状态目标优化。"},
            {"path": "agents/test_knowledge_agent.py + graph/experience_memory.py", "responsibility": "测试知识智能体的检索、学习、历史经验压缩导入和系统助手问答。"},
            {"path": "analysis/", "responsibility": "读取Python AST与Java结构并转换为统一测试状态。"},
            {"path": "executor/ + validation/", "responsibility": "适配pytest、coverage.py、JUnit、JaCoCo、PIT、变异执行和动态验证。"},
            {"path": "batch_generate_tests.py + run_all_datasets.py", "responsibility": "目录发现、隔离任务、Python并行、HumanEvalJava双槽隔离、其他Java串行、续跑、三轮处理和批量报告。"},
            {"path": "monitoring/", "responsibility": "实验登记、实时数据融合、队列启动、知识问答和前端接口。"},
            {"path": "frontend/src/", "responsibility": "可视化展示与交互，只消费监控数据，不参与智能体决策。"},
        ],
        "dataset_families": [
            {"name": "TestEval", "language": "Python", "scope": "文件/函数/类任务"},
            {"name": "HumanEval", "language": "Python", "scope": "文件/函数任务"},
            {"name": "HumanEvalJava", "language": "Java", "scope": "文件/类任务"},
            {"name": "Defects4J", "language": "Java", "scope": "类/项目任务", "subsets": ["cli", "csv", "gson", "lang3"]},
        ],
        "languages": [
            {
                "id": "python",
                "name": "Python",
                "source_extensions": [".py"],
                "test_framework": "pytest",
                "coverage_tools": ["coverage.py"],
                "mutation_tools": ["项目内变异执行器"],
                "analysis": ["Python AST", "函数/类/方法识别", "动态类型观察", "异步函数", "生成器", "异常与模式匹配"],
                "generated_test": "test_*.py",
                "evidence": ["收集与执行", "行/分支覆盖", "运行时类型", "断言有效性", "变异检测"],
            },
            {
                "id": "java",
                "name": "Java",
                "source_extensions": [".java"],
                "test_framework": "JUnit 5",
                "coverage_tools": ["JaCoCo"],
                "mutation_tools": ["PIT"],
                "analysis": ["Tree-sitter Java", "类/接口/枚举/记录", "继承与泛型", "重载与Override", "分支/循环/异常"],
                "generated_test": "*Test.java",
                "evidence": ["编译与JUnit", "JaCoCo行/分支覆盖", "PIT变异", "断言有效性"],
            },
        ],
        "scopes": [
            {"id": "file", "name": "单文件级", "entry": "main.py", "description": "针对一个Python或Java源码文件构建共享TSG并生成测试。"},
            {"id": "class", "name": "单类级", "entry": "main.py", "description": "分析源码文件中的目标类、方法和状态关系，生成类级测试。"},
            {"id": "project", "name": "项目/目录级", "entry": "batch_generate_tests.py", "description": "递归发现目录中的可测试源码，逐任务执行并生成批量报告。"},
            {"id": "datasets", "name": "全数据集级", "entry": "run_all_datasets.py", "description": "运行HumanEval、TestEval、HumanEvalJava和Defects4J源码组并支持完整续跑。"},
        ],
        "phases": [
            {"id": "discover", "name": "目标发现", "owner": "测试状态智能体", "description": "识别语言、测试范围、类、方法、分支、循环、异常和依赖。", "artifacts": ["StructuredContext", "源码结构证据"]},
            {"id": "state", "name": "测试状态构建", "owner": "测试状态智能体", "description": "构建并检查共享TSG，状态缺失或损坏时自主分析和修复。", "artifacts": ["state_flow_graph.json", "共享TSG版本"]},
            {"id": "retrieve", "name": "知识检索", "owner": "测试知识智能体", "description": "按语言、结构、质量历史和时间衰减检索可用经验。", "artifacts": ["KnowledgeContext", "经验ID"]},
            {"id": "plan", "name": "测试意图规划", "owner": "测试状态智能体", "description": "根据状态缺口决定下一智能体、具体任务、目标节点和停止条件。", "artifacts": ["TestIntentPlan", "AgentDecision"]},
            {"id": "generate", "name": "生成与候选验证", "owner": "测试生成智能体", "description": "生成Python/Java测试，检查语法、导入、编译、候选结构和测试意图一致性。", "artifacts": ["候选测试文件", "ValidationEvidence"]},
            {"id": "execute", "name": "执行与工具验证", "owner": "测试生成智能体", "description": "内部迭代先执行快速筛查，准备形成正式结果时再执行完整变异/PIT评估；最终报告只采用完整评估证据。", "artifacts": ["ExecutionReport", "筛查证据", "完整覆盖/变异/断言证据"]},
            {"id": "evaluate", "name": "状态评估与路由", "owner": "测试状态智能体", "description": "结合执行、覆盖、断言和变异证据评估状态，决定修复、优化、知识检索或结束。", "artifacts": ["EvaluationFeedback", "A-E等级", "下一任务"]},
            {"id": "learn", "name": "经验学习", "owner": "测试知识智能体", "description": "归纳成功、失败和无收益动作，更新独立测试知识引导库。", "artifacts": ["KnowledgeUpdated", "长期经验"]},
        ],
        "agents": [
            {
                "id": "state",
                "name": "测试状态智能体",
                "mission": "维护可信测试状态，并动态决定下一步由谁完成什么任务。",
                "inputs": ["源码结构", "共享TSG", "执行验证证据", "知识上下文", "质量阈值"],
                "outputs": ["测试状态中心更新", "质量等级", "缺口排序", "测试意图", "下一任务规划"],
                "modules": [
                    {"id": "state_analysis", "name": "状态分析", "description": "检查程序、测试、运行和决策证据是否完整。"},
                    {"id": "state_repair", "name": "状态自修复", "description": "在共享TSG状态缺失、损坏或语义不足时重新分析并修复状态。"},
                    {"id": "quality_evaluation", "name": "质量评估", "description": "综合执行、覆盖、断言、变异和状态证据进行A-E分级。"},
                    {"id": "gap_analysis", "name": "缺口分析", "description": "定位覆盖、断言、变异、边界、运行类型和有效性缺口。"},
                    {"id": "next_task_planning", "name": "下一任务规划", "description": "决定自己修复状态，或调度知识检索、生成、修复、优化和结束。"},
                ],
            },
            {
                "id": "generation",
                "name": "测试生成智能体",
                "mission": "把测试意图转成可运行、可验证、可修复和可优化的高质量测试。",
                "inputs": ["TestIntentPlan", "目标源码", "知识提示", "修复建议", "已有测试"],
                "outputs": ["测试代码", "执行验证证据", "状态定位修复结果", "状态目标优化结果"],
                "modules": [
                    {"id": "generation", "name": "测试生成", "description": "按语言、测试框架、目标路径和边界生成候选测试。"},
                    {"id": "candidate_validation", "name": "候选验证", "description": "检查语法、结构、调用方式、测试意图和弱断言。"},
                    {"id": "execution_validation", "name": "执行验证", "description": "调用pytest/JUnit、coverage/JaCoCo、变异/PIT并收集真实结果。"},
                    {"id": "state_positioning_repair", "name": "状态定位修复", "description": "根据失败状态定位直接因素，只修改必要断言、方法、类或文件并保护已有有效测试。"},
                    {"id": "state_target_optimization", "name": "状态目标优化", "description": "根据最大质量缺口增强覆盖、断言、边界、运行类型或变异检测能力。"},
                ],
            },
            {
                "id": "knowledge",
                "name": "测试知识智能体",
                "mission": "检索、学习和解释测试知识，并负责用户的单元测试领域对话。",
                "inputs": ["任务签名", "状态缺口", "历史结果", "用户问题", "实验报告"],
                "outputs": ["知识提示", "经验记录", "失败措施", "带来源的对话回答"],
                "modules": [
                    {"id": "retrieval", "name": "经验检索", "description": "为每一轮规划和生成检索最相关的成功与失败经验。"},
                    {"id": "learning", "name": "经验学习", "description": "归纳本轮有效策略、失败原因、质量收益和应避免动作。"},
                    {"id": "conversation", "name": "知识对话", "description": "与已配置大模型共同定位实验、任务和报告，回答单元测试问题并归纳可验证概念。"},
                ],
            },
        ],
        "quality_metrics": [
            {"id": "execution", "name": "运行与通过", "description": "测试可收集或编译、可运行且结果通过。"},
            {"id": "coverage", "name": "覆盖证据", "description": "Python coverage.py或Java JaCoCo产生的行、分支和组合覆盖。"},
            {"id": "branch", "name": "分支覆盖BC", "description": "已执行分支占可识别分支的比例，缺少工具证据时不填零。"},
            {"id": "ae", "name": "断言有效性AE", "description": "断言可达性、具体性和行为判别能力。"},
            {"id": "mutation", "name": "变异检测", "description": "有效变异体被测试杀死的比例及其可靠性。"},
            {"id": "time", "name": "任务耗时Time/s", "description": "任务跨续跑累计耗时，单位为秒；不等同于测试执行次数。"},
            {"id": "pass_rate", "name": "执行通过率PassRate", "description": "最终收集到测试且执行通过的任务占全部选定任务的比例。"},
            {"id": "avg_exec", "name": "平均执行次数AvgExec", "description": "每任务实际启动测试的工具会话数；联合测试与覆盖计一次，PIT的一次变异评估计一次，缓存与仅编译收集不计。"},
            {"id": "tir", "name": "目标改善率TIR", "description": "执行前登记的评价目标中，具有可比较保留结果且得到改善的比例；同时展示可比较及缺证数量。"},
        ],
        "execution_policies": [
            {"id": "python_parallel", "name": "Python任务调度", "value": "默认4任务并行", "description": "独立源码任务使用隔离输出目录并行处理；每个任务内部的执行、覆盖和变异工具保持串行。"},
            {"id": "python_screening", "name": "Python变异快速筛查", "value": "每任务最多8个", "description": "优先选择存活变异、未覆盖位置和状态缺口附近的变异体，只用于内部优化决策，不作为正式成绩。"},
            {"id": "python_final", "name": "Python正式变异评估", "value": "最多20个，复用筛查结果", "description": "准备保存有效结果时只补做筛查阶段尚未执行的变异体，正式报告、质量分级和知识学习使用完整结果。"},
            {"id": "llm_parallel", "name": "本地模型调度", "value": "最多2请求并发", "description": "Python任务可以并行，但本地Ollama请求采用独立并发上限，避免同时占满显存。"},
            {"id": "round_budget", "name": "三轮优先级", "value": "R1基线 · R2恢复D/E · R3优化C", "description": "先恢复不可用任务，再统一增强全部C；每轮内部修复或优化最多3次并在达标、无变化或无增益时提前停止，不开启R4。"},
            {"id": "quality_thresholds", "name": "质量判定", "value": "先可行，再尽可能提质", "description": "A/B/C首先要求测试可运行并具有正常行为和有效断言；覆盖、断言和可靠变异证据用于区分质量层次，缺失的不适用指标不虚记高分。"},
            {"id": "java_serial", "name": "Java评估策略", "value": "HumanEvalJava默认2个隔离槽；其他Java全局串行", "description": "类级HumanEvalJava使用独立工作区并冻结每轮知识视图；JUnit与JaCoCo合并执行，正式候选运行PIT。项目级Java与其他Java目录保持原串行策略。"},
            {"id": "evaluation_cache", "name": "评估证据缓存", "value": "源码+测试+本地依赖+运行环境", "description": "输入和工具环境未变化时复用覆盖、变异和Java工具链证据；任一相关内容变化即自动失效。"},
            {"id": "resume", "name": "目录续跑", "value": "完成目录跳过", "description": "完整目录直接跳过；未完成目录保留已完成轮次，只继续缺失任务或应进入下一轮的任务。"},
        ],
        "artifacts": [
            {"name": "共享TSG", "path": "state_flow_graph.json", "content": "程序状态、测试状态、运行证据、决策状态及其关系。"},
            {"name": "任务摘要", "path": "stateflow_summary.json", "content": "单任务实际质量、轮次、失败、知识使用和生成测试路径。"},
            {"name": "轮次进度", "path": "experiment_round_progress.json", "content": "R1/R2/R3等级轨迹、当前策略和最佳产物。"},
            {"name": "失败报告", "path": "task_failure_report_R1/R2.json/html", "content": "D/E失败阶段、原因、错误、已有措施和建议措施。"},
            {"name": "批量摘要", "path": "batch_summary.json", "content": "任务总数、A-E分布、轮次统计、平均质量和失败列表。"},
            {"name": "目录完成标记", "path": "dataset_completion.json", "content": "只有目录全部任务形成A/B/C有效结果时才允许整目录跳过。"},
            {"name": "实时运行状态", "path": "batch_runtime.json", "content": "活动任务、排队任务、工作槽、模型通道和运行时间。"},
            {"name": "长期知识", "path": "test_knowledge_guidance.json", "content": "跨实验保留的成功模式、失败规避、优化经验和对话概念。"},
        ],
        "interfaces": [
            {"name": "实验总览", "content": "实验组合、A-E统计、动态执行路由、实时事件控制台、当前任务质量和全任务综合质量。"},
            {"name": "启动实验", "content": "从网页提交单文件、目录、项目或数据集任务，并为本次实验选择实际模型配置。"},
            {"name": "测试状态中心", "content": "查看共享TSG节点、关系、证据和状态元数据。"},
            {"name": "多智能体协作台", "content": "查看三个智能体的动态活动、能力证据、共享TSG数据交换和滚动交互控制台。"},
            {"name": "测试生成过程", "content": "查看真实过程活动、Python/Java工具链、状态事件和逐任务耗时折线图。"},
            {"name": "任务与报告", "content": "按任务查看实际指标、轮次、失败和生成产物。"},
            {"name": "测试知识引导库", "content": "查看已掌握、正在学习、待复核和应避免的知识及其真实验证次数。"},
            {"name": "系统在线", "content": "作为唯一系统能力入口，查看语言、范围、能力、指标、工具、运行策略和连接状态。"},
            {"name": "系统助手", "content": "由测试知识智能体联合后台同一大模型查询实验、报告、知识与系统能力。"},
        ],
    }
